export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_TOTAL_COUNT = "INCREASE_TOTAL_COUNT";
export const DECREASE_TOTAL_COUNT = "DECREASE_TOTAL_COUNT";
